### ISSUE TITLE
Remove copy restriction on us-west-1 ami-0a85a3a3fb34b3c7f

### ISSUE THREAD

**Issue by KaneRodriguez** [bentoml/stable-diffusion-bentoml#6]
## Issue

Unable to copy ami-0a85a3a3fb34b3c7f from us-west-1 to us-east-2. When attempting to do so, I get the error:
```bash
You do not have permission to access the storage of this ami
```

## Steps to recreate

1. Sign into aws as an account that did not create the ami
2. Follow instructions [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/CopyingAMIs.html#ami-copy-steps)
3. See error

## Suggested Resolution

Remove copy restriction on the ami

**Comment by yubozhao** [comment]
cc @jjmachan

**Comment by jjmachan** [comment]
You can can use an AMI from `us-east-2` for example `ami-004cebb118c02866e`.

**Comment by yubozhao** [comment]
@KaneRodriguez Can you test it?

**Comment by dav009** [comment]
any updates on `ami-0a85a3a3fb34b3c7f` ? I cant access it

**Comment by Itsdarkhere** [comment]
This is from the readme:

Note: This default configuration only works in the us-west-1 region. Choose the corresponding AMI Id in your region from [AWS AMI Catalog](https://console.aws.amazon.com/ec2/home#AMICatalog) to deploy to your desired region.
